project_id = "nxaztzpuqdivemdemvga"

[functions.mood-tts]
verify_jwt = false

[functions.generate-recipe]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-quiz-image]
verify_jwt = false

[functions.generate-news]
verify_jwt = false

[functions.fetch-real-news]
verify_jwt = false

[functions.generate-mood-tips]
verify_jwt = false

[functions.generate-zodiac-wellness]
verify_jwt = false

[functions.generate-career-insights]
verify_jwt = false

[functions.generate-career-details]
verify_jwt = false