project_id = "nxaztzpuqdivemdemvga"

[functions.mood-tts]
verify_jwt = false

[functions.generate-recipe]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-quiz-image]
verify_jwt = false